### ISSUE TITLE
[feature request] add option to disable a feed

### ISSUE THREAD

**Issue by MaDill** [Etuldan/spaRSS#179] opened 2016-04-05 07:56 UTC
Sometimes I'm not interested in a feed on my list, but I don't want to delete it, because later I will read it again. For this an option in the list configuration would be nice to disable a feed.

For example I plan my next vacation and read a lot of travel feeds. When everything is scheduled and booked I want to disable then till my next vacation is near by. For this the disable would be nice.

**Comment by ildar** [comment] 2016-04-05 08:56
Duplicate of https://github.com/Etuldan/spaRSS/issues/30
Please search first, then file issues.

**Closed** 2016-04-05 09:34 UTC
Labels: duplicate
